name: Playwright Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies (skip tests)
        run: mvn install -DskipTests

      - name: Install Playwright Browsers
        run: mvn exec:java -e -Dexec.mainClass="com.microsoft.playwright.CLI" -Dexec.args="install 
--with-deps"

      - name: Install Xvfb (required for headed mode)
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Run Playwright tests
        run: |
          if [ "$CI" = "true" ]; then
            echo "Running in CI with Xvfb..."
            xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" mvn test
          else
            echo "Running locally without Xvfb..."
            mvn test
          fi
